"""Confined worker child for the dispatcher's response usage scan.

Run by ``usage_scan_jail.py`` as::

    python -m core.llm.dispatcher._usage_scan_child <socketpair-fd>

One long-lived worker per dispatcher process. It receives the bounded
head/tail windows of a relayed LLM response body over a socketpair,
scans them with the pure core in ``_usage_scan.py``, and returns a
JSON usage verdict — nothing else. All interpretation of the
remote-backend response bytes happens HERE, inside the confinement
below, never in the dispatcher process that holds provider
credentials.

Wire protocol (both directions): length-prefixed frames —
``>II`` header = payload length (bytes) + request id, then the
payload. Payloads are hard-capped at ``MAX_FRAME_PAYLOAD`` on both
ends; an oversized or inconsistent frame is a protocol violation and
this process EXITS (the parent kills/books-failed/respawns — never
guesses). Request payload: the ``_REQ_META`` fixed sub-header
(``>IIHB`` = head length, tail length, content-type length, flags
with bit 0 = truncated) followed by the content-type bytes, the head
bytes, and the tail bytes — all raw, no encoding. Response payload:
JSON ``{"model": str|null, "input_tokens": int, "output_tokens": int,
"cache_read_tokens": int, "cache_creation_tokens": int}`` — exactly
what ``scan_usage`` returns.
Request ids are generated by the parent from ``os.urandom`` (this
process only echoes them); unpredictable ids plus the parent's
pre-send check for unsolicited buffered bytes stop a hostile worker
from pre-queueing a frame to be consumed as a later request's
verdict. The response echoes the request id; the parent treats a
mismatch as desync and kills the worker. Frame id ``READY_FRAME_ID``
(0) is reserved for the one startup ready frame:
``{"ready": true|false, "landlock": bool, "pid": int[, "error": str]}``.

Self-confinement at startup, in order (the same ladder as
``core/sandbox/_parser_jail_child.py``, which this worker deliberately
mirrors without importing — the modules confine different parse
surfaces and evolve independently):

1. Close every inherited fd except stdio (parent binds them to
   /dev/null) and the socketpair fd, which is then pinned to fd 3.
2. ``check_landlock_available()`` — probed BEFORE the rlimits because
   its functional self-test forks a probe child and writes a /tmp
   probe file, both of which the rlimits below forbid.
3. rlimits: CPU (lifetime budget — a runaway scan dies and the parent
   respawns), AS, NOFILE, FSIZE=0 (this process writes no files;
   PYTHONDONTWRITEBYTECODE is set by the parent so imports don't
   try), NPROC=0 (no forks ever again).
4. Landlock (when available): read-only on the code trees this
   interpreter actually runs from, no writes anywhere, EXEC scoped to
   the same trees, CONNECT_TCP handled with zero rules (no network).
   Installation failure on a Landlock-capable kernel is FATAL — the
   ready frame reports the error and the parent fails closed.
   A Landlock-less kernel proceeds degraded (rlimits + fd hygiene +
   process isolation only) and says so in the ready frame; the parent
   is responsible for making that loud.

Exit is silent and clean on EOF from the parent (parent death or
deliberate stop): the socketpair is the lifeline, no reaping logic
needed. stdout/stderr go to /dev/null — diagnostics travel in the
ready frame; post-startup failures surface to the parent as this
process's exit.
"""

import json
import os
import resource
import socket
import struct
import sys
from pathlib import Path

from core.llm.dispatcher._usage_scan import scan_usage

# ---- wire protocol (single source of truth; the parent-side manager
# imports these) ----
FRAME_HEADER = struct.Struct(">II")
# Request meta sub-header: head length, tail length, content-type
# length, flags (bit 0 = the relay's truncated marker).
REQ_META = struct.Struct(">IIHB")
FLAG_TRUNCATED = 0x01
# The relay retains at most 256 KiB of head + 256 KiB of tail
# (`_UsageScanner`'s window caps); 640 KiB covers both windows plus
# the content-type and meta sub-header with headroom, while still
# rejecting a runaway frame outright. Verdict JSON is far smaller —
# its only unbounded field (the model string) is a substring of the
# capped windows.
MAX_FRAME_PAYLOAD = 640 * 1024
# Reserved id for the one startup ready frame.
READY_FRAME_ID = 0

# ---- confinement parameters ----
# CPU: lifetime budget for the whole worker, not per-scan — the
# parent's per-scan round-trip timeout fires long before this; the
# rlimit is the backstop that kills a wedged/hostile worker outright
# (parent observes EOF, books that scan as failed, respawns). Unlike
# the CONNECT parser (per-tunnel), usage scans recur once per relayed
# response for the whole run, so the parent also RECYCLES the worker
# proactively (see usage_scan_jail._RECYCLE_AFTER_SCANS) — this limit
# must stay comfortably above the recycle window's worst-case honest
# CPU (500 scans x a pathological 100 ms = 50 s), and low enough that
# a wedged worker still dies promptly rather than spinning for
# minutes with the relay's booking blocked behind it.
_RLIMIT_CPU_S = 120
# AS: a bare interpreter with this module's imports measures ~20 MiB
# VSZ; 512 MiB is generous headroom (AS counts virtual, not resident)
# while still capping an allocation-bomb scan input.
_RLIMIT_AS_BYTES = 512 * 1024 * 1024
_RLIMIT_NOFILE = 64
_SOCK_FD = 3


def _close_inherited_fds(keep_fd: int) -> None:
    """Close every fd except stdio and *keep_fd* (the socketpair)."""
    soft, _hard = resource.getrlimit(resource.RLIMIT_NOFILE)
    upper = 65536 if soft == resource.RLIM_INFINITY else min(int(soft), 65536)
    if keep_fd > 3:
        os.closerange(3, keep_fd)
    os.closerange(keep_fd + 1, upper)


def _set_limit(res: int, value: int) -> None:
    """setrlimit(res, (value, value)), clamped to the inherited hard cap.

    An unprivileged process cannot RAISE a hard limit; if the
    dispatcher already runs under a tighter cap, tighter is fine —
    take the minimum instead of failing the spawn.
    """
    _soft, hard = resource.getrlimit(res)
    if hard != resource.RLIM_INFINITY:
        value = min(value, hard)
    resource.setrlimit(res, (value, value))


def _apply_rlimits() -> None:
    _set_limit(resource.RLIMIT_CPU, _RLIMIT_CPU_S)
    _set_limit(resource.RLIMIT_AS, _RLIMIT_AS_BYTES)
    _set_limit(resource.RLIMIT_NOFILE, _RLIMIT_NOFILE)
    # No file writes, ever: the first byte written to a regular file
    # raises SIGXFSZ and kills the worker. The socketpair is unaffected
    # (FSIZE governs regular files only).
    _set_limit(resource.RLIMIT_FSIZE, 0)
    # No forks: NPROC 0 makes fork()/clone() fail with EAGAIN. Applied
    # AFTER check_landlock_available(), whose functional self-test
    # needs one probe fork.
    _set_limit(resource.RLIMIT_NPROC, 0)


def _readable_code_paths() -> "list[str]":
    """The trees this worker legitimately reads: its own code, nothing else.

    The RAPTOR tree is located from THIS module's on-disk position —
    for a read grant that is the correct anchor by construction (the
    grant must cover the tree the code actually imported from, not
    whatever a stale environment variable names). Interpreter prefixes
    come from python_runtime_tool_paths() (empty for a system python,
    whose prefixes live under the system dirs granted explicitly).
    Missing paths (e.g. /lib64 on some distros) are skipped non-fatally
    by the Landlock grant resolver.
    """
    from core.sandbox.python_paths import python_runtime_tool_paths

    raptor_dir = str(Path(__file__).resolve().parents[3])
    return [raptor_dir, *python_runtime_tool_paths(),
            "/usr", "/lib", "/lib64", "/etc"]


def _recv_exact(sock: socket.socket, n: int) -> "bytes | None":
    """Read exactly *n* bytes; None on EOF (clean or mid-frame)."""
    buf = b""
    while len(buf) < n:
        chunk = sock.recv(n - len(buf))
        if not chunk:
            return None
        buf += chunk
    return buf


def _send_frame(sock: socket.socket, req_id: int, payload: bytes) -> None:
    sock.sendall(FRAME_HEADER.pack(len(payload), req_id) + payload)


def _serve(sock: socket.socket) -> int:
    """One response-window scan in, one verdict out, forever.

    Returns 0 on clean EOF from the parent, 1 on any protocol
    violation — never guess, just die; the parent treats worker death
    as book-failed-and-respawn.
    """
    while True:
        header = _recv_exact(sock, FRAME_HEADER.size)
        if header is None:
            return 0  # parent closed — normal shutdown
        length, req_id = FRAME_HEADER.unpack(header)
        if (length > MAX_FRAME_PAYLOAD or length < REQ_META.size
                or req_id == READY_FRAME_ID):
            return 1
        payload = _recv_exact(sock, length)
        if payload is None:
            return 0
        head_len, tail_len, ct_len, flags = REQ_META.unpack(
            payload[:REQ_META.size])
        if REQ_META.size + ct_len + head_len + tail_len != length:
            return 1  # inconsistent meta — protocol violation
        offset = REQ_META.size
        ct_bytes = payload[offset:offset + ct_len]
        offset += ct_len
        head = payload[offset:offset + head_len]
        offset += head_len
        tail = payload[offset:offset + tail_len]
        content_type: "str | None" = (
            ct_bytes.decode("utf-8", "replace") if ct_len else None)
        verdict = scan_usage(
            head, tail,
            truncated=bool(flags & FLAG_TRUNCATED),
            content_type=content_type,
        )
        _send_frame(sock, req_id, json.dumps(verdict).encode("utf-8"))


def main(argv: "list[str]") -> int:
    if len(argv) != 2:
        return 2
    fd = int(argv[1])
    _close_inherited_fds(fd)
    if fd != _SOCK_FD:
        os.dup2(fd, _SOCK_FD)
        os.close(fd)
    sock = socket.socket(fileno=_SOCK_FD)

    # Landlock availability probe BEFORE the rlimits (it forks a
    # self-test child and writes a /tmp probe file). The import also
    # happens here, before restrict-reads could interfere with module
    # loading — as does the closure BUILD (grant-path resolution reads
    # the filesystem).
    from core.sandbox.landlock import (
        LandlockInstallError,
        _make_landlock_preexec,
        check_landlock_available,
    )

    landlock_ok = check_landlock_available()
    apply_landlock = None
    if landlock_ok:
        apply_landlock = _make_landlock_preexec(
            [],  # no writable paths — this worker writes nothing
            readable_paths=_readable_code_paths(),
            deny_all_tcp_connect=True,
            fail_raise=True,
        )

    _apply_rlimits()

    if apply_landlock is not None:
        try:
            apply_landlock()
        except LandlockInstallError as exc:
            # Landlock is available on this kernel but the policy
            # would not install: fail CLOSED. Report the reason in the
            # ready frame so the parent can log it, then exit — the
            # parent refuses in-process scanning on a capable kernel.
            _send_frame(sock, READY_FRAME_ID, json.dumps({
                "ready": False, "landlock": True, "pid": os.getpid(),
                "error": f"landlock install failed: {exc}",
            }).encode("utf-8"))
            return 1

    _send_frame(sock, READY_FRAME_ID, json.dumps({
        "ready": True, "landlock": landlock_ok, "pid": os.getpid(),
    }).encode("utf-8"))

    return _serve(sock)


if __name__ == "__main__":
    sys.exit(main(sys.argv))
