"""Confined worker child for the egress proxy's request-line parser.

Run by ``parser_jail.py`` as::

    python -m core.sandbox._parser_jail_child <socketpair-fd>

One long-lived worker per orchestrator process. It receives raw CONNECT
request-line bytes over a socketpair, parses them with the pure parser
in ``_request_head.py``, and returns a JSON verdict — nothing else. All
interpretation of hostile request-head bytes happens HERE, inside the
confinement below, never in the orchestrator process.

Wire protocol (both directions): length-prefixed frames —
``>II`` header = payload length (bytes) + request id, then the payload.
Payloads are hard-capped at ``MAX_FRAME_PAYLOAD`` on both ends; an
oversized or truncated frame is a protocol violation and this process
EXITS (the parent kills/denies/respawns — never guesses). Request
payload: the raw request-line bytes verbatim (no encoding). Response
payload: JSON ``{"ok": true, "host": str, "port": int}`` or
``{"ok": false, "reason": str, "host": str|null, "port": int|null,
"census": str}`` (``census`` = the method-census classification from
``_request_head.CENSUS_VALUES``; accepted lines are census "connect"
by construction and carry no field).
Request ids are generated by the parent from ``os.urandom`` (this
process only echoes them); unpredictable ids plus the parent's
pre-send check for unsolicited buffered bytes stop a hostile worker
from pre-queueing a frame to be consumed as a later request's verdict.
The response echoes the request id; the parent treats a mismatch as
desync and kills the worker. Frame id ``READY_FRAME_ID`` (0) is
reserved for the one startup ready frame:
``{"ready": true|false, "landlock": bool, "pid": int[, "error": str]
[, "rlimits_failed": [str, ...]]}`` — ``error`` names the startup
stage and exception when ready is false (stderr is /dev/null, so the
frame is the only diagnostic channel); ``rlimits_failed`` lists any
limits that could not be applied (best-effort per limit; the parent
warns loudly).

Self-confinement at startup, in order:

1. Close every inherited fd except stdio (parent binds them to
   /dev/null) and the socketpair fd, which is then pinned to fd 3.
2. ``check_landlock_available()`` — probed BEFORE the rlimits because
   its functional self-test forks a probe child and writes a /tmp
   probe file, both of which the rlimits below forbid.
3. rlimits (best-effort per limit; failures ride the ready frame and
   the parent warns): CPU (lifetime budget — a runaway parse dies and
   the parent respawns), AS, NOFILE, FSIZE=0 (this process writes no
   files; PYTHONDONTWRITEBYTECODE is set by the parent so imports
   don't try), NPROC=0 (no forks ever again).
4. Landlock (when available): read-only on the code trees this
   interpreter actually runs from, no writes anywhere, EXEC scoped to
   the same trees, CONNECT_TCP handled with zero rules (no network).
   Installation failure on a Landlock-capable kernel is FATAL — the
   ready frame reports the error and the parent fails closed.
   A Landlock-less kernel proceeds degraded (rlimits + fd hygiene +
   process isolation only) and says so in the ready frame; the parent
   is responsible for making that loud.

Exit is silent and clean on EOF from the parent (parent death or
deliberate stop): the socketpair is the lifeline, no reaping logic
needed. stdout/stderr go to /dev/null — diagnostics travel in the
ready frame; post-startup failures surface to the parent as this
process's exit.
"""

import json
import os
import resource
import socket
import struct
import sys
from pathlib import Path

from core.sandbox._request_head import ParsedRequestLine, parse_connect_request_line

# ---- wire protocol (single source of truth; the parent-side manager
# imports these) ----
FRAME_HEADER = struct.Struct(">II")
# Request lines are capped at 4096 bytes by the proxy's reader and the
# JSON verdicts are small; anything near this cap is a protocol error.
MAX_FRAME_PAYLOAD = 8192
# Reserved id for the one startup ready frame.
READY_FRAME_ID = 0

# ---- confinement parameters ----
# CPU: lifetime budget for the whole worker, not per-request — the
# parent's per-request round-trip timeout fires long before this; the
# rlimit is the backstop that kills a wedged/hostile worker outright
# (parent observes EOF, denies the in-flight request, respawns).
_RLIMIT_CPU_S = 60
# AS: a bare interpreter with this module's imports measures ~20 MiB
# VSZ; 512 MiB is generous headroom (AS counts virtual, not resident)
# while still capping an allocation-bomb parse input.
_RLIMIT_AS_BYTES = 512 * 1024 * 1024
_RLIMIT_NOFILE = 64
_SOCK_FD = 3


def _close_inherited_fds(keep_fd: int) -> None:
    """Close every fd except stdio and *keep_fd* (the socketpair)."""
    soft, _hard = resource.getrlimit(resource.RLIMIT_NOFILE)
    upper = 65536 if soft == resource.RLIM_INFINITY else min(int(soft), 65536)
    # The socketpair fd can legitimately sit at/above a small soft cap
    # (fds above the soft limit exist when the limit was lowered after
    # they were opened) — never let the cap truncate the sweep short
    # of the one fd this process is built around.
    upper = max(upper, keep_fd + 1)
    if keep_fd > 3:
        os.closerange(3, keep_fd)
    os.closerange(keep_fd + 1, upper)


def _set_limit(res: int, value: int) -> None:
    """setrlimit(res, (value, value)), clamped to the inherited hard cap.

    An unprivileged process cannot RAISE a hard limit; if the
    orchestrator already runs under a tighter cap, tighter is fine —
    take the minimum instead of failing the spawn.
    """
    _soft, hard = resource.getrlimit(res)
    if hard != resource.RLIM_INFINITY:
        value = min(value, hard)
    resource.setrlimit(res, (value, value))


def _apply_rlimits() -> "list[str]":
    """Apply the worker rlimits; best-effort PER LIMIT.

    Returns a description of every limit that could not be applied
    (empty = all applied), which rides the ready frame so the parent
    can warn loudly. Best-effort matches the repo's rlimit precedent
    (core/sandbox/preexec.py logs and continues): platform semantics
    vary — macOS accepts but does not enforce RLIMIT_AS, counts
    RLIMIT_NPROC user-wide with a kern.maxprocperuid clamp, and other
    platforms have their own quirks — and the rlimits are the belt of
    this worker's floor, not the wall. A partially-applied set with a
    LOUD parent-side warning beats an unattributed worker death that
    takes the fail-closed jail (and every proxied request) down on
    hosts where one setrlimit misbehaves.
    """
    failures: "list[str]" = []
    for name, res, value in (
        ("cpu", resource.RLIMIT_CPU, _RLIMIT_CPU_S),
        ("as", resource.RLIMIT_AS, _RLIMIT_AS_BYTES),
        ("nofile", resource.RLIMIT_NOFILE, _RLIMIT_NOFILE),
        # No file writes, ever: the first byte written to a regular
        # file raises SIGXFSZ and kills the worker. The socketpair is
        # unaffected (FSIZE governs regular files only).
        ("fsize", resource.RLIMIT_FSIZE, 0),
        # No forks: NPROC 0 makes fork()/clone() fail with EAGAIN.
        # Applied AFTER check_landlock_available(), whose functional
        # self-test needs one probe fork.
        ("nproc", resource.RLIMIT_NPROC, 0),
    ):
        try:
            _set_limit(res, value)
        except (OSError, ValueError) as exc:
            failures.append(f"{name}: {type(exc).__name__}: {exc}")
    return failures


def _readable_code_paths() -> "list[str]":
    """The trees this worker legitimately reads: its own code, nothing else.

    The RAPTOR tree is located from THIS module's on-disk position —
    for a read grant that is the correct anchor by construction (the
    grant must cover the tree the code actually imported from, not
    whatever a stale environment variable names). Interpreter prefixes
    come from python_runtime_tool_paths() (empty for a system python,
    whose prefixes live under the system dirs granted explicitly).
    Missing paths (e.g. /lib64 on some distros) are skipped non-fatally
    by the Landlock grant resolver.
    """
    from core.sandbox.python_paths import python_runtime_tool_paths

    raptor_dir = str(Path(__file__).resolve().parents[2])
    return [raptor_dir, *python_runtime_tool_paths(),
            "/usr", "/lib", "/lib64", "/etc"]


def _recv_exact(sock: socket.socket, n: int) -> "bytes | None":
    """Read exactly *n* bytes; None on EOF (clean or mid-frame)."""
    buf = b""
    while len(buf) < n:
        chunk = sock.recv(n - len(buf))
        if not chunk:
            return None
        buf += chunk
    return buf


def _send_frame(sock: socket.socket, req_id: int, payload: bytes) -> None:
    sock.sendall(FRAME_HEADER.pack(len(payload), req_id) + payload)


def _serve(sock: socket.socket) -> int:
    """One request-line in, one verdict out, forever. 0 on clean EOF."""
    while True:
        header = _recv_exact(sock, FRAME_HEADER.size)
        if header is None:
            return 0  # parent closed — normal shutdown
        length, req_id = FRAME_HEADER.unpack(header)
        if length > MAX_FRAME_PAYLOAD or req_id == READY_FRAME_ID:
            # Protocol violation — never guess, just die; the parent
            # treats worker death as deny-and-respawn.
            return 1
        payload = _recv_exact(sock, length)
        if payload is None:
            return 0
        result = parse_connect_request_line(payload)
        if isinstance(result, ParsedRequestLine):
            verdict: dict = {
                "ok": True, "host": result.host, "port": result.port,
            }
        else:
            verdict = {
                "ok": False, "reason": result.reason,
                "host": result.host, "port": result.port,
                # Method census for the proxy's counters — only this
                # process sees the split method. Accepted lines are
                # census "connect" by construction, so ok=true frames
                # carry no census field.
                "census": result.census,
            }
        _send_frame(sock, req_id, json.dumps(verdict).encode("utf-8"))


def main(argv: "list[str]") -> int:
    if len(argv) != 2:
        return 2
    fd = int(argv[1])
    _close_inherited_fds(fd)
    if fd != _SOCK_FD:
        os.dup2(fd, _SOCK_FD)
        os.close(fd)
    # Explicit family/type: the fd is always one end of the parent's
    # AF_UNIX SOCK_STREAM socketpair, so say so instead of relying on
    # socket.socket(fileno=...) auto-detection — that detection is
    # platform-variable (no SO_DOMAIN outside Linux) and a failure
    # here would be an unattributable pre-frame death.
    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM, 0,
                         fileno=_SOCK_FD)

    # From here the socket is up, so EVERY startup failure must be
    # ATTRIBUTED: a bare exception would unwind past the ready frame
    # and the parent would see only an EOF ("closed the socket") with
    # the traceback lost to the /dev/null stderr — exactly the
    # undebuggable shape this staging exists to prevent. The
    # fail-closed LandlockInstallError arm keeps its own frame text
    # (the parent's refuse-to-serve contract keys off a probe-capable
    # kernel failing the install; see parser_jail.py).
    stage = "landlock probe"
    try:
        # Landlock availability probe BEFORE the rlimits (it forks a
        # self-test child and writes /tmp probe artifacts). The import
        # also happens here, before restrict-reads could interfere with
        # module loading — as does the closure BUILD (grant-path
        # resolution reads the filesystem).
        from core.sandbox.landlock import (
            LandlockInstallError,
            _make_landlock_preexec,
            check_landlock_available,
        )

        landlock_ok = check_landlock_available()
        apply_landlock = None
        if landlock_ok:
            stage = "landlock closure build"
            apply_landlock = _make_landlock_preexec(
                [],  # no writable paths — this worker writes nothing
                readable_paths=_readable_code_paths(),
                deny_all_tcp_connect=True,
                fail_raise=True,
            )

        stage = "rlimits"
        rlimits_failed = _apply_rlimits()

        if apply_landlock is not None:
            stage = "landlock install"
            try:
                apply_landlock()
            except LandlockInstallError as exc:
                # Landlock is available on this kernel but the policy
                # would not install: fail CLOSED. Report the reason in
                # the ready frame so the parent can log it, then exit —
                # the parent refuses to serve without a confined worker.
                _send_frame(sock, READY_FRAME_ID, json.dumps({
                    "ready": False, "landlock": True, "pid": os.getpid(),
                    "error": f"landlock install failed: {exc}",
                }).encode("utf-8"))
                return 1
    except Exception as exc:  # noqa: BLE001 — attribution frame: any startup failure must reach the parent, not vanish as EOF
        try:
            _send_frame(sock, READY_FRAME_ID, json.dumps({
                "ready": False, "landlock": False, "pid": os.getpid(),
                "error": (f"startup failed at {stage}: "
                          f"{type(exc).__name__}: {exc}"),
            }).encode("utf-8"))
        except OSError:
            pass  # socket already gone — EOF is all we can offer
        return 1

    ready: dict = {
        "ready": True, "landlock": landlock_ok, "pid": os.getpid(),
    }
    if rlimits_failed:
        ready["rlimits_failed"] = rlimits_failed
    _send_frame(sock, READY_FRAME_ID, json.dumps(ready).encode("utf-8"))

    return _serve(sock)


if __name__ == "__main__":
    sys.exit(main(sys.argv))
